BuyEveryDayIfBelowAverage:
  ExecutionTime: "12:00"
  CodeAndQuantity:
    # Nongsim holdings
    - code: "072710"
      quantity: 1
    # Woori financial
    - code: "316140"
      quantity: 4
    # DBG financial
    - code: "139130"
      quantity: 4
    # KBstar 200
    - code: "148020"
      quantity: 5
BuyEveryDayIfLowerThan:
  ExecutionTime: "12:05"
  CodeAndQuantityAndPrice:
  # KBStar 200
  - code: "148020"
    quantity: 10
    price: 29000
  # KT&G
  - code: "033780"
    quantity: 1
    price: 80000
  # Shinhan
  - code: "055550"
    quantity: 10
    price: 32000
  # Woori financial
  - code: "316140"
    quantity: 10
    price: 11300
  # Giub bank
  - code: "024110"
    quantity: 30
    price: 9600
  # SamSung Electronics
  - code: "005930"
    quantity: 10
    price: 60000
  # SamSung card
  - code: "029780"
    quantity: 1
    price: 28400