name: remote ssh command
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "34.30.133.186"
        username: "sungguklim"
        key: ${{ secrets.KEY }}
        port: "22"
        script: |
          whoami
          cd /home/sungguklim/program_store/mykoreainvestment
          git pull
